#!/usr/bin/env node
/**
 * Regenerates src/generated/types.ts from the server's OpenAPI spec.
 *
 * Usage:
 *   node scripts/gen-types.mjs           regenerate src/generated/types.ts in place
 *   node scripts/gen-types.mjs --check   regenerate into a temp file and diff against
 *                                        the committed file; exit 1 if they differ
 *
 * The generator itself is deterministic (openapi-typescript@7 on a fixed spec
 * path), so `--check` only fails when the spec changed and nobody re-ran the
 * generator.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
// Standalone exports bundle the spec locally; the monorepo shares its parent spec.
// GRAPHANN_SPEC overrides either location for one-off regeneration.
const LOCAL_SPEC_PATH = join(ROOT, "api", "openapi", "spec.yaml");
const SPEC_PATH =
  process.env.GRAPHANN_SPEC ??
  (existsSync(LOCAL_SPEC_PATH) ? LOCAL_SPEC_PATH : join(ROOT, "..", "api", "openapi", "spec.yaml"));
const OUT_PATH = join(ROOT, "src/generated/types.ts");
const GENERATOR_PKG = "openapi-typescript@7";

const OPENAPI_TYPESCRIPT_BANNER =
  "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */\n";

const HEADER = `/**
 * GENERATED — do not hand-edit.
 *
 * Source:     api/openapi/spec.yaml
 * Generator:  npx --yes ${GENERATOR_PKG} <spec> -o src/generated/types.ts
 * Regenerate: pnpm run gen:types      (from the SDK root)
 * Verify:     pnpm run gen:types:check
 *
 * Fix drift by editing the spec and re-running the generator, never this file.
 */
`;

/** Runs the generator into `destPath` and normalizes its header. */
function generate(destPath) {
  execFileSync("npx", ["--yes", GENERATOR_PKG, SPEC_PATH, "-o", destPath], {
    stdio: ["ignore", "ignore", "inherit"],
  });
  const raw = readFileSync(destPath, "utf8");
  const body = raw.startsWith(OPENAPI_TYPESCRIPT_BANNER)
    ? raw.slice(OPENAPI_TYPESCRIPT_BANNER.length)
    : raw;
  writeFileSync(destPath, HEADER + body);
  execFileSync(
    process.execPath,
    [
      join(ROOT, "node_modules/prettier/bin/prettier.cjs"),
      "--write",
      "--config",
      join(ROOT, ".prettierrc.json"),
      destPath,
    ],
    { stdio: ["ignore", "ignore", "inherit"] },
  );
}

function main() {
  const check = process.argv.includes("--check");

  if (!check) {
    generate(OUT_PATH);
    console.log(`Wrote ${OUT_PATH}`);
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), "graphann-ts-gen-"));
  const tmpOut = join(tmpDir, "types.ts");
  try {
    generate(tmpOut);
    const committed = readFileSync(OUT_PATH, "utf8");
    const fresh = readFileSync(tmpOut, "utf8");
    if (committed !== fresh) {
      console.error(
        "src/generated/types.ts is STALE: regenerating from the spec produces a " +
          "different file than what's committed.\n" +
          "Run `pnpm run gen:types` and commit the result.",
      );
      process.exitCode = 1;
      return;
    }
    console.log("src/generated/types.ts is up to date with the spec.");
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

main();
