/**
 * Public entry point for `@graphann/client`.
 *
 * Re-exports only the surface application code needs. Internal helpers
 * (singleflight, retry math, cache) stay unexported to keep the API small
 * and the bundle tree-shakable.
 */

export { Client } from "./client.js";

export {
  AuthenticationError,
  AuthorizationError,
  ConflictError,
  GraphANNError,
  NetworkError,
  NotFoundError,
  PayloadTooLargeError,
  RateLimitError,
  ServerError,
  UnexpectedStatusError,
  ValidationError,
} from "./errors.js";

export type { ClientOptions } from "./options.js";
export { SDK_VERSION } from "./options.js";

export { Paginator } from "./pagination.js";

export type {
  AddDocumentsRequest,
  AddDocumentsResponse,
  APIKey,
  AdminBackupList,
  AdminBackupRow,
  APIKeyListItem,
  APIKeyStatusResponse,
  APIKeyStatusTenantRow,
  BackupChunkInfo,
  BackupManifest,
  BackupMeta,
  BackupScheduleStatus,
  BackupSummary,
  BatchSearchRequest,
  BatchSearchResponse,
  BatchSearchResult,
  BulkDeleteByExternalIdsRequest,
  BulkDeleteByExternalIdsResponse,
  BulkDeleteDocumentsRequest,
  BulkDeleteDocumentsResponse,
  ChunkResponse,
  ClearIndexResponse,
  ClearPendingResponse,
  CleanupOrphansResponse,
  ClusterHealthResponse,
  ClusterNode,
  ClusterNodesResponse,
  ClusterShard,
  ClusterShardsResponse,
  CompactAllResponse,
  CompactAllSkipped,
  CompactIndexResponse,
  CompressionType,
  CreateAPIKeyRequest,
  CreateBackupResponse,
  CreateIndexRequest,
  CreateTenantRequest,
  DeleteBackupResponse,
  DeleteChunksResponse,
  DeleteDocumentResponse,
  DeleteLLMSettingsResponse,
  DeleteTenantResponse,
  Document,
  DocumentChunk,
  EmbedSpaceAdminResponse,
  EmbedSpaceIndexRow,
  FlushIndexResponse,
  GCResponse,
  GetDocumentResponse,
  HealthResponse,
  ImportDocumentsResponse,
  IndexID,
  IndexInfo,
  IndexStatus,
  IndexStatusResponse,
  Job,
  JobID,
  JobKind,
  JobProgress,
  JobStatus,
  LicenseAuditEvent,
  LicenseStatus,
  ListAllBackupsOptions,
  ListAPIKeysResponse,
  ListBackupsResponse,
  ListDocumentEntry,
  ListDocumentsOptions,
  ListDocumentsPage,
  ListIndexesResponse,
  ListJobsOptions,
  ListJobsResponse,
  ListTenantsResponse,
  LiveIndexStats,
  LLMProvider,
  LLMSettings,
  LLMSettingsPatch,
  MultiSearchRequest,
  MultiSearchResponse,
  MultiSearchResult,
  OrgDocumentInput,
  OrgIndexListResponse,
  OrgSyncDocumentsRequest,
  OrgSyncDocumentsResponse,
  Page,
  PendingStatusResponse,
  ProcessPendingResponse,
  ReadyResponse,
  RebuildGraphResponse,
  RequestOptions,
  RestoreBackupRequest,
  RestoreBackupResponse,
  SearchFilter,
  SearchRequest,
  SearchResponse,
  SearchResult,
  ServerErrorEnvelope,
  SharedIndexListResponse,
  SwitchEmbeddingModelRequest,
  SwitchEmbeddingModelResponse,
  Tenant,
  TenantID,
  TenantQuotaResponse,
  UpdateIndexRequest,
  UpdateLLMSettingsResponse,
  UpdateTenantQuotaRequest,
  UpsertResourceRequest,
  UpsertResourceResponse,
} from "./types.js";
